---
- name: Make Aegir's Nginx config available
  file:
    state: link
    path: /etc/nginx/conf.d/aegir.conf
    src: "{{ aegir_root }}/config/nginx.conf"
    force: yes  # the target doesn't exist yet


